deployment:
  name: myweb
  replicas: 3
  containerName: httpd
  containerImage: httpd
  cpuRequest: 100m
  memoryRequest: 50Mi
  #cpuLimit: 400m
  #memoryLimit: 200Mi
  initContainerName: generator
  initContainerImage: alpine
  initContainerCommand: ['sh', '-c', 'echo "<html> Welcome to Kubernetes </html>" > /docroot/index.html']

service:
  name: myweb-service
  selector:
    app: myweb
  port: 80
  targetPort: 80
  serviceType: NodePort
